export const SUBMIT_CONNEXION = "SUBMIT_CONNEXION";
export const FETCH_ANIMALS = "FETCH_ANIMALS";
export const UPDATE_FAVORIS = "UPDATE_FAVORIS";
export const FETCH_CAGNOTES = "FETCH_CAGNOTES";
export const UPDATE_CAGNOTE = "UPDATE_CAGNOTE";
export const FETCH_CAGNOTE = "FETCH_CAGNOTE";
